### ISSUE TITLE
Build fails : src/setup_links.py : No such file or directory

### ISSUE THREAD

**Issue by sasmaster** [vsimon/webrtcbuilds#70]
Hi,building on Windows. Some python script file can't be found.Here is the terminal output:

> Error: Command 'D:\\emsdk\\python\\2.7.5.3_64bit\\python.exe src/build/landmines.py --landmine-scripts src/tools_webrtc/get_landmines.py --src-dir src' returned non-zero exit status 1 in D:\webrtcbuilds\out
> /d/webrtcbuilds/util.sh: line 148: src/setup_links.py: No such file or directory

**Comment by qwertzui11** [comment]
I got the same issue
Revision, Master
OS Win7 64bit
gclient is the latest and in the PATH
latest Python 2.7
visual studio 2015 is installed.

```
./build.sh
Host OS: win
Target OS: win
Target CPU: x64
Checking webrtcbuilds dependencies
Checking depot-tools
Bootstrapping cipd client for windows-386 from https://chrome-infra-packages.ap
pspot.com/client?platform=windows-386&version=git_revision:d2677a4477e59cb7de00
f1fb8a00e96b1aaeb927...
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Failed to update depot_tools.
Usage: gclient.py <command> [options]

Meta checkout dependency manager for Git.

Commands are:
  config   creates a .gclient file in the current directory
  diff     displays local diff for every dependencies
  fetch    fetches upstream commits for all modules
  flatten  flattens the solutions into a single DEPS file
  grep     greps through git repos managed by gclient
  help     prints list of commands or help for a specific command
  pack     generates a patch which can be applied at the root of the tree
  recurse  operates [command args ...] on all the dependencies
  revert   reverts all modifications in every dependencies
  revinfo  outputs revision info mapping for the client and its dependencies
  root     outputs the solution root (or current dir if there isn't one)
  runhooks runs hooks for files that have been modified in the local working copy
  status   shows modification status for every dependencies
  sync     checkout/update all modules
  validate validates the .gclient and DEPS syntax
  verify   verifies the DEPS file deps are only from allowed_hosts

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -j JOBS, --jobs=JOBS  Specify how many SCM commands can run in parallel;
                        defaults to 8 on this machine
  -v, --verbose         Produces additional output for diagnostics. Can be
                        used up to three times for more logging info.
  --gclientfile=CONFIG_FILENAME
                        Specify an alternate .gclient file
  --spec=SPEC           create a gclient file containing the provided string.
                        Due to Cygwin/Python brokenness, it can't contain any
                        newlines.
  --cache-dir=CACHE_DIR
                        (git only) Cache all git repos into this dir and do
                        shared clones from the cache, instead of cloning
                        directly from the remote. (experimental)
  --no-nag-max          Ignored for backwards compatibility.
Building revision: a750333372f45d785f746d6cf308e4e7d87b83ac
Associated revision number: 20554
Checking out WebRTC revision (this will take awhile): a750333372f45d785f746d6cf308e4e7d87b83ac
Running: 'C:\Python27\python.exe' 'C:\bla\build_dependencies\webrtc\webrtcbuilds\depot_tools\gclient.py' root
Running: 'C:\Python27\python.exe' 'C:\bla\build_dependencies\webrtc\webrtcbuilds\depot_tools\gclient.py' config --spec 'solutions = [
  {
    "url": "https://webrtc.googlesource.com/src.git",
    "managed": False,
    "name": "src",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: 'C:\Python27\python.exe' 'C:\bla\build_dependencies\webrtc\webrtcbuilds\depot_tools\gclient.py' sync --nohooks --with_branch_heads
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Syncing projects: 100% (33/33), done.

________ running 'C:\Python27\python.exe src/build/landmines.py --landmine-scripts src/tools_webrtc/get_landmines.py --src-dir src' in 'C:\bla\build_dependencies\webrtc\webrtcbuilds\out'



Please follow the instructions at https://www.chromium.org/developers/how-tos/build-instructions-windows


Traceback (most recent call last):
  File "src/build/landmines.py", line 148, in <module>
    sys.exit(main())
  File "src/build/landmines.py", line 135, in main
    gyp_environment.SetEnvironment()
  File "C:\bla\build_dependencies\webrtc\webrtcbuilds\out\src\build\gyp_environment.py", line 30, in SetEnvironment
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\bla\build_dependencies\webrtc\webrtcbuilds\out\src\build\vs_toolchain.py", line 44, in SetEnvironmentAndGetRuntimeDllDirs
    update_result = Update()
  File "C:\bla\build_dependencies\webrtc\webrtcbuilds\out\src\build\vs_toolchain.py", line 436, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\bla\\build_dependencies\\webrtc\\webrtcbuilds\\out\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\bla\\build_dependencies\\webrtc\\webrtcbuilds\\out\\src\\build\\win_toolchain.json', '88c3b62e1eb0893b8cd57e3f4859c3af27907f64']' returned non-zero exit status 1
Hook ''C:\Python27\python.exe' src/build/landmines.py --landmine-scripts src/tools_webrtc/get_landmines.py --src-dir src' took 19.75 secs
Error: Command 'C:\\Python27\\python.exe src/build/landmines.py --landmine-scripts src/tools_webrtc/get_landmines.py --src-dir src' returned non-zero exit status 1 in C:\bla\build_dependencies\webrtc\webrtcbuilds\out
/c/bla/build_dependencies/webrtc/webrtcbuilds/util.sh: line 148: src/setup_links.py: No such file or directory
+ exit 1
```
